// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package frontend

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func indexBaseConfig() BaseConfig {
	return BaseConfig{
		Bulma:       true,
		Toast:       true,
		Fontawesome: true,
		Aos:         true,
		Footer:      true,
		Navbar:      true,
	}
}

func Index(exampleArg string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- additional css per page --> <style type=\"text/css\">\n            div.hero-body {\n                text-align: center;\n                margin-top: 52px;\n            }\n        </style> <!-- Header --> <div class=\"hero-body\" data-aos=\"fade-in\"><div class=\"container\">Welcome to<h1 class=\"title is-1\">Example.de</h1><h2 class=\"subtitle is-3\">test test test ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(exampleArg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/index.templ`, Line: 32, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2></div></div><!-- Box element --> <div class=\"container has-text-centered\" data-aos=\"fade-in\"><div class=\"column is-6 is-offset-3\"><h3 class=\"title\">Please configure your TLS scan</h3><!-- has-text-black --><!-- <hr class=\"login-hr\"/> --><p class=\"subtitle\">Enter your details.</p><div class=\"box\"><!-- determine which route to call --><form action=\"/scan\" method=\"POST\"><div class=\"field\"><div class=\"control\"><input class=\"input is-warning\" type=\"text\" name=\"numberscans\" placeholder=\"Enter the number of scans\" autofocus=\"\"></div></div><div class=\"field\"><div class=\"control\"><label class=\"checkbox\"><!-- define name attribute to catch value in backend with c.FormValue(name_value) --><!-- in the below input, name_value=checkboxValue --><input type=\"checkbox\" name=\"checkboxValue\"> concurrency enabled?</label></div></div><div class=\"field\"><label class=\"label\">API List</label><div class=\"control\"><div class=\"select\"><select name=\"apilistname\"><option>api.banking.csv</option> <option>popular.websites.csv</option></select></div></div></div><button type=\"submit\" class=\"button is-block is-warning is-light is-fullwidth\">Scan <i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i></button></form></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout1(indexBaseConfig()).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
