// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package scripts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func InitToast(msgtext string, err bool) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_InitToast_938b`,
		Function: `function __templ_InitToast_938b(msgtext, err){if (msgtext != "") {
        setTimeout(function () {
            if (!err) {
                bulmaToast.toast({ message: msgtext, type: 'is-success' });
            } else {
                bulmaToast.toast({ message: msgtext, type: 'is-danger' });
            }
        }, 500);
    }
}`,
		Call:       templ.SafeScript(`__templ_InitToast_938b`, msgtext, err),
		CallInline: templ.SafeScriptInline(`__templ_InitToast_938b`, msgtext, err),
	}
}
